---
- hosts: webservers
  become: yes
  vars:
      username: Raghu
      doc_root: /var/www/html/
  tasks:
      - name: Copy site file
        template: src=templates/index.html dest={{doc_root}}/index.html mode=0644
